spring.application.name=teste
app.admin.login=admin
app.admin.password=admin123
spring.datasource.url=jdbc:h2:file:./data/prensa-rolamentos;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
server.port=8080
